### ISSUE TITLE
Wiki: "student always going to bathroom"

### ISSUE THREAD

**Issue by superstealthysheep** [eado/mPass#4]
> You're a science teacher. One of your students _always_ is going to the bathroom. You have decided to give all of your students hall passes so that they can only leave the classroom a certain number of times per term.

The sentence "One of your students is _always_ going to the bathroom." implies that it is one student that basically  _lives_ in the bathroom, while the point you're trying to communicate is that there is almost always _a_ student in the bathroom. An appropriate substitution would be "There's _always_ one of your students who wants to go to the bathroom."

P.S. could you add me as a contributer?

**Comment by TheRealPhotonic** [comment]
The phrase "There's *always* one of your students going to the bathroom" seems to refer to multiple students. The previous explanation made more sense to me, as it refers to one student; it shouts "that student" louder than "those students".

...Does this make sense? Tell me if you need any more clarification, eheh.

**Comment by eado** [comment]
Yeah...ask @jack-the-coder about this. He wrote it.

**Comment by eado** [comment]
Fixed it anyways. Check the wiki again.
